[package]
name = "resume"
version = "0.1.0"
authors = ["cliff roberts <roberts.cliff@gmail.com>"]

[dependencies]
printpdf = "0.2.6"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
argparse = "0.2.1"